<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ForeverIPhones</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            line-height: 1.6;
        }

        header {
            background-color: #333;
            color: white;
            padding: 1em 0;
            text-align: center;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        nav ul li {
            display: inline;
            margin: 0 15px;
        }

        nav ul li a {
            color: white;
            text-decoration: none;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
        }

        section {
            padding: 2em 0;
            border-bottom: 1px solid #ccc;
        }

        .product {
            border: 1px solid #ddd;
            padding: 1em;
            margin: 1em 0;
            display: flex;
            align-items: center;
        }

        .product img {
            width: 150px;
            height: auto;
            margin-right: 20px;
        }

        footer {
            text-align: center;
            padding: 1em 0;
            background-color: #333;
            color: white;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>
    <header>
        <h1>ForeverIPhones</h1>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#products">Products</a></li>
                <li><a href="#about">About Us</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#support">Support</a></li>
                <li><a href="#blog">Blog</a></li>
                <li><a href="#contact">Contact Us</a></li>
            </ul>
        </nav>
    </header>

    <div class="container">
        <section id="home">
            <h2>Welcome to ForeverIPhones</h2>
            <p>Your one-stop shop for all things iPhone. We offer refurbished, pre-owned, and brand new iPhones under the guidance of Wandile and S'lindokuhle.</p>
        </section>

        <section id="products">
            <h2>Our Products</h2>
            <div class="product">
                <img src="https://via.placeholder.com/150" alt="iPhone 13 Pro">
                <div>
                    <h3>iPhone 13 Pro</h3>
                    <p>Brand New: The ultimate iPhone experience with advanced technology.</p>
                </div>
            </div>
            <div class="product">
                <img src="https://via.placeholder.com/150" alt="iPhone 12">
                <div>
                    <h3>iPhone 12</h3>
                    <p>Refurbished: Experience the power and speed of the iPhone 12 at a reduced price.</p>
                </div>
            </div>
            <div class="product">
                <img src="https://via.placeholder.com/150" alt="iPhone SE">
                <div>
                    <h3>iPhone SE</h3>
                    <p>Pre-owned: A compact and affordable iPhone with great features, gently used and tested.</p>
                </div>
            </div>
        </section>

        <section id="about">
            <h2>About Us</h2>
            <p>At ForeverIPhones, we are dedicated to providing the best iPhone products and services. Our team, led by Wandile and S'lindokuhle, is passionate about technology and customer satisfaction. We are located in KZN, at Hibberdene.</p>
        </section>

        <section id="services">
            <h2>Our Services</h2>
            <p>We offer a range of services including repair, trade-ins, and financing plans to meet all your iPhone needs.</p>
        </section>

        <section id="support">
            <h2>Support</h2>
            <p>If you have any questions or need assistance, our support team is here to help. Visit our FAQ page or contact us directly.</p>
        </section>

        <section id="blog">
            <h2>Blog</h2>
            <p>Stay updated with the latest iPhone tips, tricks, and news. Check out our latest blog posts.</p>
        </section>

        <section id="contact">
            <h2>Contact Us</h2>
            <p>We'd love to hear from you! Reach out to us through our contact form or visit us at our store in Hibberdene, KZN.</p>
        </section>
    </div>

    <footer>
        <p>&copy; 2024 ForeverIPhones. All rights reserved.</p>
    </footer>
</body>
</html>
